1. ValueError now thrown when 'n < 0' in function 'factorial' 
2. print(factorial(5)) now executed when __name__ == "__main__"